### ISSUE TITLE
luks option seems to get ignored using BTRFS root

### ISSUE THREAD

**Issue by hollaho** [tokiclover/mkinitramfs-ll#37]
I have a initramfs build with

mkinitramfs -Hbtrfs --all --usrdir=/usr/share/mkinitramfs-ll/usr/ --keymap=de -k4.0.5-gentoo

and the kernel is compiled with the initramfs embedded and called via EFI boot

efibootmgr -c -L Gentoo-4.0.5-2 -l vmlinuz-4.0.5-gentoo root=LABEL=croot rootfs=:Yes btrfs=root-sda5 luks=pwd

But it asks for the plain boot partition "init: Type in valid block device" (seemingly ignoring the luks=pwd) and bails into rescue shell when I enter sda5 e.g.
I can then use cryptsetup open /dev/sda5 root and mount the underlying btrfs filesystem to /newroot and then it boots after an exit command. So all works, but the script just does not handle the luks/btrfs correct I think.

This is the /run/init.log by the way:
[0]: umask 0077
[0]: mkdir -p dev/pts proc run sys /newroot /mnt/tok
[0]: mount -t proc proc /proc
[0]: mount -t sysfs sysfs /sys
[0]: mount -t devtmpfs devtmpfs /dev
[0]: /sbin/mdev -s
[0]: mount -t tmpfs -o mode=755,size=1% tmpfs /run
[0]: MODPROBE kms
[0]: ln -fns /proc/self/fd /dev/fd
[0]: ln -fns fd/2 /dev/stderr
[0]: ln -fns fd/0 /dev/stdin
[0]: ln -fns fd/1 /dev/stdout
[0]: loadfont
[0]: loadkmap
[1]: test -f /etc/issue
[0]: test -n /dev/mapper/enc_root
[0]: get_key 
[0]: blk /dev/mapper/enc_root DEV
[0]: get_dev /dev/mapper/enc_root ROOT 1
[255]: mount -o ro /dev/sda5 /newroot

----

There is no dev/mapper/enc_root created of course. I checked this.

**Comment by tokiclover** [comment]
There is no need to append `-Hbtrfs` When using `--all|-a` command line switch because `{btrfs,zram}` hooks are included. Similarly, no need to append the `--usrdir=/usr/share/mkinitramfs-ll/usr/ ` because this is the default for a standard installation.

The last lines of your log show that some environment variables are already set to handle a crypted device, hence the lines dealing with `enc_root`, which explain why the `root=LABEL=croot rootfs=:Yes btrfs=root-sda5 luks=pwd` kernel command line argument is ignored.

If editing the kernel command line argument is possible, append `env=:root:rootfs:luks:btrfs:` to disable the internal environment variables and enable your command line: `env=:root:rootfs:luks:btrfs: root=LABEL=croot rootfs=:Yes btrfs=root-sda5 luks=pwd`.

If booting fails, append the output of `export -p` command with your report.

It seems you setted some environment variables in mkinitramfs-ll.conf. Actually, you can use
`env=( root=LABEL=croot rootfs=:Yes btrfs=root-sda5 luks=pwd )` and be done with your kernel command line and then remove it from GRUB or EFI bootloader.

**Comment by tokiclover** [comment]
Caution: You will need to rebuild the initramfs, hence the kernel for you if using the `env` settings in mkinitramfs-ll.conf. Second, just put your command line in `env` variable (which might not be an array if using plain POSIX shell.)

**Comment by hollaho** [comment]
I have changed the kernel command line to

Boot000A* Gentoo-4.0.5-3        HD(1,800,200000,c764177c-24c3-419a-9613-a16e824e04a6)File(vmlinuz-4.0.5-gentoo)env=:root:rootfs:luks:btrfs: root=LABEL=croot rootfs=:Yes btrfs=root-sda5 luks=pwd

Same problem, here is the output of export -p:
export CONFDIR='/etc/mkinitramfs-ll'
export CONSOLE='/dev/console'
export ENV_CHK='false'
export HISTFILE='/root/.ash_history'
export HOME='/root'
export HOOKS=''
export KEYMODE='none'
export LEVEL='3m'
export LIBDIR='/lib/mkinitramfs-ll'
export LOGFILE='/run/init.log'
export MNTDIR='/mnt/tok'
export NEWROOT='/newroot'
export PATH='/sbin:/bin:/usr/bin:/usr/sbin'
export PS1='-(rsh:$(tty | cut -c6-):$PWD)-# '
export PS2='-# '
export PWD='/'
export SHLVL='2'
export SPLASHD='false'
export TERM='linux'
export _='newroot/'
export enc_root='/dev/sda5'
export init='/sbin/init'
export root='/dev/mapper/enc_root'
export rootflags='ro'
export rootfstype='btrfs'
export sh='/bin/sh'

As a side note, if I just use this command "mkinitramfs --all --keymap=de -k4.0.5-gentoo" I do get another error:
>>> building initramfs-4.0.5-gentoo...
/tmp/initramfs-4.0.5-gentoo-XXXXXX /home/schleusner
 * mkinitramfs-ll.bash: /share/mkinitramfs-ll/usr dir not found

so I need to set it to /usr/share. Not really sure why, this is a standard gentoo install from the bar overlay:
eix mkinitramfs
[I] sys-kernel/mkinitramfs-ll [1]
     Available versions:  (~)0.21.0 (~)0.21.1 **9999 {aufs +bash btrfs bzip2 device-mapper dm-crypt dmraid +e2fs f2fs fbsplash gzip jfs lz4 lzma lzo mdadm reiserfs squashfs xfs +xz zfs +zram zsh}
     Installed versions:  0.21.1(20:50:59 16.06.2015)(bash btrfs bzip2 device-mapper e2fs lzma xz zram -aufs -dm-crypt -dmraid -f2fs -fbsplash -gzip -jfs -lz4 -lzo -mdadm -reiserfs -squashfs -xfs -zfs -zsh)
     Homepage:            https://github.com/tokiclover/mkinitramfs-ll
     Description:         Lightweight, modular and powerfull initramfs genrating tool

[1] "bar" /var/lib/layman/bar

**Comment by tokiclover** [comment]
usrdir is fixed... this was introduced with 0.21.0 refactorization. Well, easily spoted.

As you can pretty much see yourself, you have `root` seted to another value and the whole command line is ignored. If everything goes fine, you should observe the kernel command line arguments as environment variables in the rescue shell. So, you should rebuild the initramfs after editing `mkiniramfs-ll.conf` and rebuild your kernel because that EFI bootloader command line has absolutely no effect. You should be able to reboot safely after that. By the way, you'd rather use an uncompressed initramfs for this in-kernel stub by appending `--compressor=none` and leave the compression to the kernel.

**NOTE:** You can fix the `usrdir` issue by editing `/usr/sbin/mkiniramfs-ll.bash`, line 187 to:
```
 :	${opts[-usrdir]:=${opts[-d]:-/usr/share/"${PKG[name]}"/usr}}
```
because there is a missing `/usr` prefix in the value of `opts[-usrdir]`.

It seems you tried to set that `root=/dev/mapper/enc_root` line from genkernel which would never work here because mkinitramfs-ll is not related in any way to genkernel.

**Comment by tokiclover** [comment]
Sync your overlays and merge mkinitralmfs-ll-0.21.3 which I've released a few minutes ago because it contains a tiny fix for btrfs hooks (ref. for details is here b15c381 -- just an unexported variable issue) before building a new initramfs. (That bug fix release install correctly documentation/resources files which are are not completely without interest for new users.)

**Comment by hollaho** [comment]
Thanks a lot for the help! I finally got it working!

There were actually 2 problems working together:

1. I had set a kernel command line in the kernel config. This was intended as a fallback but it seems the kernel handles this different and always sends the compiled in kernel command line, just appending whatever is given as real command line. And that then gets ignored. Not intuitive and I misunderstood this.
Lesson learned: Use either a manual command line or the kernel compile cmdline, never both.

So I removed the command line fallback in .config and surprise - it still did not work. But the bogus root was gone - now no root= was there at all. WTF?

2. I checked cat /proc/cmdline and saw that only garbage (some binary crap) had arrived as cmdline. So I removed the command line from the EFI boot entry and compiled it into the kernel instead.
Voila, works. After a hiccup. I first though the boot was stuck, but then I realized I have to enter the password blindly and it worked.

Lesson 2 learnt: EFI BIOS are so buggy, even when they read back the correct command line with "egibootmgr -v", they may still pass on garbage.

------------------

Suggestion: Have luks=pwd output some kind of password prompt so that the user knows he has to now type the password...

**Comment by tokiclover** [comment]
Did you merge v0.21.3 beforehand? Do you mean you used kernel .config file to set up your command line on mkinitramfs-ll.conf? Either way, it's good to hear you get it working.

Lastly, cryptsetup prompt on console to enter a password; the init script does nothing special here, although it could print something colorful before to help; and so, users would spot when to enter a pass phrase. It seems, either you missed this, or else, the console device was not initialized in time--booting does not take much time but only kernel initialization and entering a pass phrase anyway with no udev intialization. Do you notice some messages printed on the console... like those saying "switching root..." and such?

Waiting your response before closing this ticket.

**Comment by tokiclover** [comment]
Last note, I'd recommend a reliable boot loader if you don't really need signed kernel stub... GRUB2 became an entire OS but it does its job with an extensive feature sets--LUKS, RAID, LVM, ZFS, (maybe btrfs), chain loading and such... Still, an initramfs is need to mount rootfs, however, kernel+initramfs can placed anywhere if need be.

**Comment by hollaho** [comment]
>Did you merge v0.21.3 beforehand? Do you mean you used kernel .config file to set up your command >line on mkinitramfs-ll.conf?

yes to both

> either you missed this

I missed it, because it is hidden in between many USB recognition kernel lines and such. But it is indeed there, just half a page up.

>GRUB2 became an entire OS

Exactly that is why I do hate grub with a passion and kind of like the EFI approach. But it is still buggy thanks to the motherboard BIOS guys not caring the fuck about it it seems...
